- hosts: worker1
  become: true
  tasks:
  - name: question3
    copy:
      content: "hello"
      dest: /var/www/html/index.html
    notify: apache_httpd

  handlers:
  - name: apache_httpd
    service:
      name: httpd
      state: restarted
